<div class="row">
    <div class="col-md-12 text-center">
        <h1>Classements</h1>
    </div>
</div>
<div class="row mt-20">
	<div class="form-horizontal">
	    	<!-- Event choice -->
	    	<label class="col-sm-2 control-label">Événement</label>
	    	<div class="col-sm-10">
				<select class="form-control" onchange="location = this.value">
					<?php foreach ($events as $event) { ?>
						<option 
							value="<?=$this->url('classement', ['event_id' => $event->getId()])?>"
							<?php if ($event->getId() == $selectedEvent) { ?> selected <?php } ?>>
								<?=$event->getName()?>
						</option>	
					<?php } ?>
				</select>
			</div>

			<!-- Classement type choice -->
	    	<label class="col-sm-2 control-label">Type de classement</label>
	    	<div class="col-sm-10">
				<select class="form-control" onchange="location = this.value">
					<?php foreach ($typeList as $key => $value) { ?>
		            <option
		            	<?php if($selectedType == $key) { ?> selected <?php } ?>
		            	value="<?=$this->url('classement', ['event_id' => $selectedEvent, 'type' => $key]) ?>">
		            		<?=$value?>
		            </option>
		            <?php } ?>
		        </select>
	        </div>
		</div>
    <div class="col-md-12 text-center">
        <div class="table-responsive mt-20">
            <table class="table">
                <thead>
                    <tr>
                    	<?php 
                    		// Define sort type (ASC or DESC) for the display of the arrow (chevron)
                    		$glyphiconClass = '';
                    		// Define the next sort type after clicking on the same chevron
                    		$nextSortType = '';
                    		if ($this->sortType == 'ASC') {
                    			$glyphiconClass = 'glyphicon-chevron-down';
                    			$nextSortType = 'DESC';
                    		} else {
                    			$glyphiconClass = 'glyphicon-chevron-up';
                    			$nextSortType = 'ASC';
                    		}

                    		foreach ($sortList as $key => $value) { 
                    			$spanClass = 'glyphicon ';
                    			$sortType = '';
                    			if ($key == $selectedSort) {
                    				$spanClass .= $glyphiconClass;
                    				$sortType = $nextSortType;
                    			} else {
                    				$spanClass .= 'glyphicon-chevron-down disabled';
                    				$sortType = 'ASC';
                    			}
                    			?>
                    			<td>
		                        	<a href="<?=$this->url('classement', ['event_id' => $selectedEvent, 'type' => $selectedType, 'sort' => $key, 'sortType' => $sortType])?>" class="sort-link">
		                        		<?=$value?> 
		                        		<span class="<?=$spanClass?>"></span>
		                        	</a>
		                        </td>
                    		<?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php if($this->participants){ ?>
                        <?php
                        /** @var \Application\Entity\User $participant */
                        foreach($this->participants as $participant){ ?>
                            <tr>
                                <td><?=$participant->getDossardNumber()?></td>
                                <td><?=$participant->getFirstname()?></td>
                                <td><?=$participant->getLastname()?></td>
                                <td><?=empty($participant->getMeasuredTime()) ? 'N/C' : $participant->getMeasuredTime()?></td>
                            </tr>
                        <?php } ?>
                    <?php } ?>

                </tbody>
            </table>
        </div>
    </div>
</div>

